<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Da Vinci Code (Abridged Edition) P_4896eb</name>
   <tag></tag>
   <elementGuidId>4388630a-018b-4daa-be4d-fff33779b0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcbdb44d-c58a-42c5-8802-8ff2e0882958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>d7a72e03-eb65-40c7-9a86-6daf5bc914cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-extra-large celwidget</value>
      <webElementGuid>2e319b49-8013-46bb-bec0-f6a49071d933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>ra4d89-9w4qbd-29fhf3-lrklhn</value>
      <webElementGuid>d87c7bdf-af79-4b98-946d-2c5e13e06002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cel-widget</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>5759e4a3-9dfc-45c3-98b3-c6fed5b22532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan </value>
      <webElementGuid>8bac5907-5026-4a6d-9d13-b41db956ef8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTitle&quot;)</value>
      <webElementGuid>c45a18bc-b049-4ab0-ae52-be9094a8f948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>6a52e3fc-4879-4e12-a93e-93c3af345c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>8b64eff3-c755-409b-a50e-02ca944bd0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Something went wrong. Please try your request again later.'])[1]/following::span[6]</value>
      <webElementGuid>f84dfdce-23fe-48f1-9aa0-e16ff32a1062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/following::span[7]</value>
      <webElementGuid>a1d21e99-4c1c-41d7-ac9b-15f1335a22b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paperback – Abridged, 3 October 2016'])[1]/preceding::span[1]</value>
      <webElementGuid>28bb998f-1b33-4efb-8ed7-caf7ee0a8128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan']/parent::*</value>
      <webElementGuid>e9aeb330-c635-4c13-bb37-058610acc335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>20d2f4d9-1fd5-4735-91f8-95d0f4878e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan ' or . = '  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan ')]</value>
      <webElementGuid>1bd14aef-ccdf-4bc0-b84e-f6036f462be7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
