<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Da Vinci Code (Abridged Edition) P_4896eb</name>
   <tag></tag>
   <elementGuidId>646156e1-62d7-4b80-8381-ec1e13feb6ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>deb04726-b43b-437d-bbed-9713cf5df50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>cece6632-470f-4130-92f9-009a2a080533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-extra-large celwidget</value>
      <webElementGuid>e6e1d2a9-2559-42f3-923b-88ffc44299ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>uy3n7t-ep1t9-o4as1d-402m5v</value>
      <webElementGuid>564d57ec-f993-462e-84f2-941caaa384c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cel-widget</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>8f8228f2-d540-47f3-8785-0fde2828bdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan </value>
      <webElementGuid>cc0cf527-4931-49b0-864d-f404af937b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTitle&quot;)</value>
      <webElementGuid>34e5b86e-3cff-446b-8512-709b67f6b747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>5fbb4de8-a481-4996-8f54-f0f39572b734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>4978fc61-5458-487e-8757-7f05d08abaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Something went wrong. Please try your request again later.'])[1]/following::span[6]</value>
      <webElementGuid>dff255f3-61c1-43f7-80f0-11d063997d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/following::span[7]</value>
      <webElementGuid>8e8c569a-2f3d-4a71-b5f3-422ec83afe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paperback – Abridged, 3 October 2016'])[1]/preceding::span[1]</value>
      <webElementGuid>300fd2f3-6992-4ae9-afa9-3cc6afbdb3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>d03a94b1-f821-4530-afb9-4138ffb63b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan ' or . = '  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan ')]</value>
      <webElementGuid>b61c882c-a291-4117-854e-99e156bcd8ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
