<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Da Vinci Code (Abridged Edition) P_4896eb</name>
   <tag></tag>
   <elementGuidId>bda03efe-9d68-4c79-b078-c51defe3d5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>df6d41d3-694f-4b91-83aa-2b97b5d9d8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>6ac2de43-f35d-4618-96da-5a1430690d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-extra-large celwidget</value>
      <webElementGuid>754c60d3-47ac-4fd1-b09e-f6b58cf9e38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>7g5qra-k5qon-8wetf7-r6bhx3</value>
      <webElementGuid>414bbc02-cba2-4d87-be24-cbd438d1ebf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cel-widget</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>417c0e33-ce8c-461a-8ae8-713f74d38c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan </value>
      <webElementGuid>27850a7c-276b-4f87-96d0-874004490a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTitle&quot;)</value>
      <webElementGuid>8012b3d6-d941-410f-a1d1-7c56d0776e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>ed288315-f5fc-4e22-aa37-acd014689b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>ee157bf2-b14c-4b60-8524-5a5250f280db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Something went wrong. Please try your request again later.'])[1]/following::span[6]</value>
      <webElementGuid>1b719e23-73eb-43bc-af3b-82d87b76dd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/following::span[7]</value>
      <webElementGuid>c4d38fc8-5dce-4a12-9bb6-a3fe714b62c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paperback – Abridged, 3 October 2016'])[1]/preceding::span[1]</value>
      <webElementGuid>83c55f7f-afe8-4ce1-93c0-f952da6bb38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan']/parent::*</value>
      <webElementGuid>44e1a032-1d75-4136-b59c-0fe4d905fa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>4054ac9a-1e32-47ae-bfb4-b64cc6da240d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan ' or . = '  The Da Vinci Code (Abridged Edition) [Paperback] Brown, Dan ')]</value>
      <webElementGuid>3246ba69-bd31-4cec-b7a9-dfe8b7bacd3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
