<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Login_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>41638587-66ab-42c0-90b8-ab13881f34b2</testSuiteGuid>
   <testCaseLink>
      <guid>eb445b4b-a2c4-4772-9394-2506786185da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon/TC_Amazon_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bd9a0f63-778b-4aa1-9135-190d73024fec</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Login_Excel/Amazon_Login_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bd9a0f63-778b-4aa1-9135-190d73024fec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8d658fe3-fe28-4b6c-ad76-60565d4cf23c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bd9a0f63-778b-4aa1-9135-190d73024fec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>3b259c8c-dd1f-4b62-bf2f-a40856f8e503</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
