<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Login_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>41638587-66ab-42c0-90b8-ab13881f34b2</testSuiteGuid>
   <testCaseLink>
      <guid>04b10a1e-6ca5-4afc-82b9-66d2e77ffa3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon/TC_Amazon_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>95fc4342-b161-49f0-bbe3-8617a47191bb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Login_Excel/Amazon_Login_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>95fc4342-b161-49f0-bbe3-8617a47191bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>5ebc4d8e-3524-4561-b646-f2b8177a9e18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>95fc4342-b161-49f0-bbe3-8617a47191bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>0c8906a5-7c91-4175-bcb2-ae985bbddc4c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
