<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your password_signInSubmit</name>
   <tag></tag>
   <elementGuidId>47039e53-fbfd-4997-bd87-06f9c5c9dbb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c720323c-7fe9-4182-99af-03ed59a4db07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInSubmit</value>
      <webElementGuid>9d0fee8f-d9aa-42a0-96c5-669b32f1cb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>af8141aa-0a5f-489c-b675-6712ede03f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>74941e75-3ab9-4f2d-a81c-64b09731ceb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c8080e85-ff16-4df5-8005-70311ba2bb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>auth-signin-button-announce</value>
      <webElementGuid>b3a9ca9d-c636-4672-b6a6-aeeb7ce4a71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInSubmit&quot;)</value>
      <webElementGuid>c67d72f3-b27f-4f9a-a37e-876adc9f45a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInSubmit']</value>
      <webElementGuid>6c8c7a2a-4937-475f-9225-e60104a439da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']/span/input</value>
      <webElementGuid>e671cbf6-b995-4afc-811a-7e02c623cfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>62fd6231-5384-48bd-89e1-b28a1fb30b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInSubmit' and @type = 'submit']</value>
      <webElementGuid>56d1b41e-38a9-4ecb-9b90-d0ed12d6c358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
