<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_-_s-image</name>
   <tag></tag>
   <elementGuidId>0cfc15e8-7179-41b5-82f9-72e028401448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[6]/div/div/div/div/span/div/div/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bf7e5c17-0d0a-462a-baa7-3aabc996a95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>6dbf4374-d6d5-4d98-b652-17e3eaeacd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL320_.jpg</value>
      <webElementGuid>3be8f08a-0f70-45a7-81c9-e4364c16e328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL320_.jpg 1x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL480_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL640_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL800_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL960_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>cd2da58f-1474-4005-9814-446c3d1923a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sponsored Ad - Milton Aura 1000 Thermosteel Bottle, 1.05 Litre, Silver | 24 Hours Hot and Cold | Easy to Carry | Rust &amp; Le...</value>
      <webElementGuid>39e563f0-7690-4361-a606-d12844854e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ee002d92-5b77-4e55-9d80-005da781264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>baf64868-f33b-4a11-bf85-5bb43e3bcd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9aa99217-f54d-44b8-885c-00974ac439be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-4-of-24 sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 AdHolder sg-col s-widget-spacing-small sg-col-4-of-20&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_4&quot;]/div[@class=&quot;rush-component s-expand-height&quot;]/div[@class=&quot;rush-component s-featured-result-item s-expand-height&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-expand-height puis-include-content-margin puis puis-vw0goty2ahaky2ds8ppx5s5mhw s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section a-spacing-base&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-spacing-small s-height-equalized puis puis-vw0goty2ahaky2ds8ppx5s5mhw&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-square-aspect&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>2b498095-03a6-44b6-b770-7387b199af53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[6]/div/div/div/div/span/div/div/div/span/a/div/img</value>
      <webElementGuid>0d0a67d3-58f7-4666-95d6-d1f654343c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sponsored Ad - Milton Aura 1000 Thermosteel Bottle, 1.05 Litre, Silver | 24 Hours Hot and Cold | Easy to Carry | Rust &amp; Le...']</value>
      <webElementGuid>24fe88aa-e247-4eba-be04-cb11d3e6bdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/span/div/div/div/span/a/div/img</value>
      <webElementGuid>47a759e4-8737-4fc2-93d3-b54c5621c690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/61iEidn19EL._AC_UL320_.jpg' and @alt = 'Sponsored Ad - Milton Aura 1000 Thermosteel Bottle, 1.05 Litre, Silver | 24 Hours Hot and Cold | Easy to Carry | Rust &amp; Le...']</value>
      <webElementGuid>125a883a-1df5-4752-b68d-24686f7ce0eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
