<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Your List</name>
   <tag></tag>
   <elementGuidId>d209ef71-8649-4e81-8709-7b8f9bd5c39e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='huc-view-your-list-button']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#huc-view-your-list-button > span.a-button-inner > a.a-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ae1db5b-9baf-47ef-9b05-19e1b6aa47a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.in/hz/wishlist/ls/QP7YPIMOZX95?ref_=wl_dp_view_your_list</value>
      <webElementGuid>2ee72754-0f5f-4d07-abb9-108c1d6e4d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>524e326a-8439-4fe5-aac4-2ae386e3f96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Your List</value>
      <webElementGuid>39c3c670-f2fd-47be-862c-1e9028ff7a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huc-view-your-list-button&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>c17df2f7-a54e-4d70-b39d-adb3d2512116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='huc-view-your-list-button']/span/a</value>
      <webElementGuid>2c88dbbf-4238-4791-815c-cc5dea7f51f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Your List')]</value>
      <webElementGuid>31ef398e-5d1a-4b2c-9a52-aaf48cf913fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping List'])[1]/following::a[2]</value>
      <webElementGuid>3576c5c3-46c6-47d0-a51a-92abe0b40a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One item added to'])[1]/following::a[3]</value>
      <webElementGuid>0ce2d4dd-96ed-4f91-9633-9c15798620e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspired by your list'])[1]/preceding::a[1]</value>
      <webElementGuid>d893eaec-5e1a-46b7-a4ae-c600d1d27447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,999.00'])[2]/preceding::a[4]</value>
      <webElementGuid>df779f30-243e-4ae5-a670-3ef62461d200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Your List']/parent::*</value>
      <webElementGuid>82928932-b4f1-44a6-b7ae-5da23fb40d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.in/hz/wishlist/ls/QP7YPIMOZX95?ref_=wl_dp_view_your_list')]</value>
      <webElementGuid>319e72e1-9eac-4a52-9c8d-88a0f5d5836b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/span/a</value>
      <webElementGuid>dc2415aa-4543-4c24-8c4c-78f0dbb902fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.in/hz/wishlist/ls/QP7YPIMOZX95?ref_=wl_dp_view_your_list' and (text() = 'View Your List' or . = 'View Your List')]</value>
      <webElementGuid>08d2ae42-a326-45e8-8b41-ac86722df427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
