<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add gift options_submit.add-to-regist_0d040a</name>
   <tag></tag>
   <elementGuidId>dba40fee-8ef5-47eb-9811-17c7b0a12c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-to-wishlist-button-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-wishlist-button-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>271ad378-8d08-406e-8a69-1e87566add08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-wishlist-button-submit</value>
      <webElementGuid>afbe1b71-3bba-4629-b2f7-a344b7deaa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.add-to-registry.wishlist</value>
      <webElementGuid>edeb8f3a-275a-423b-92d3-f0ea77572cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Wish List</value>
      <webElementGuid>45ce4a7d-2a6f-440d-b14f-cbb7e68138f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>atwl-splitbutton-main</value>
      <webElementGuid>01fe183c-11c7-42a9-9f17-d5aba23aeb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>&lt;!-- If PartialItemStateWeblab is true then, showing different Add-to-wish-list tool-tip message which is consistent with Add-to-Cart tool tip message.  -->
       To Add to Wish List, choose from options to the left</value>
      <webElementGuid>478bc4b2-35f6-4d8e-a503-7d66c8944985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>142ccd4c-5725-480e-97c2-6bd5ef6e5160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>09896f18-94ca-424a-87b7-8af8c82c66ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to Wish List</value>
      <webElementGuid>518e9152-2661-4bef-81f6-5b648b2fb638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wishListMainButton-announce</value>
      <webElementGuid>5486959a-e977-4369-84fb-232f42c3e201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-wishlist-button-submit&quot;)</value>
      <webElementGuid>fe06ec18-9546-4cb9-a847-aa91b4ac6b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-wishlist-button-submit']</value>
      <webElementGuid>43f632fa-6ced-404e-8dc7-9f4a0c379745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wishListMainButton']/span/input</value>
      <webElementGuid>9dbdfb73-b90e-4b82-a355-5d7794c12ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/input</value>
      <webElementGuid>dcdd5887-67a1-4f10-85b7-a940cdaa1a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add-to-wishlist-button-submit' and @name = 'submit.add-to-registry.wishlist' and @title = 'Add to Wish List' and @type = 'submit']</value>
      <webElementGuid>b2f89f9c-7d70-44fa-9248-f75585923d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
