<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Check each product page for other buyin_8fd263</name>
   <tag></tag>
   <elementGuidId>adddc0d0-8c95-4407-9325-7f426009b6a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[3]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5655e09d-f7ea-493b-8b88-38953c6c6e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>2acef884-f2b9-4c1a-8a1d-ee875ecbabe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/31uI5jVZ9UL._AC_UY218_.jpg</value>
      <webElementGuid>30059b2b-cc2e-4550-aa15-0239d6171462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/31uI5jVZ9UL._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/31uI5jVZ9UL._AC_UY327_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/31uI5jVZ9UL._AC_UY436_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/31uI5jVZ9UL._AC_UY500_FMwebp_QL65_.jpg 2.2935x</value>
      <webElementGuid>ed5c5020-b5a1-4ea9-8650-c3f0d3896a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sponsored Ad - bianco di puro Professional Power Blender 1400 Watts with 8 Preset Options for Smoothies, Frozen Yogurt, Sa...</value>
      <webElementGuid>347c1fb8-bf9e-4870-a183-ab1820796427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1db69bb7-96d3-444d-9fc8-8353d170f874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>cdd561a1-e0d2-4be1-b90e-4b593b97a35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d06c7f5-59b3-4175-8e0e-88f24fae5ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-result-item s-asin sg-col-0-of-12 sg-col-16-of-20 AdHolder sg-col s-widget-spacing-small sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot;]/div[@class=&quot;rush-component&quot;]/div[@class=&quot;rush-component s-featured-result-item&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-vw0goty2ahaky2ds8ppx5s5mhw s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section&quot;]/div[@class=&quot;puisg-row&quot;]/div[@class=&quot;puisg-col puisg-col-4-of-12 puisg-col-4-of-16 puisg-col-4-of-20 puisg-col-4-of-24 puis-list-col-left&quot;]/div[@class=&quot;puisg-col-inner&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-flex-expand-height puis puis-vw0goty2ahaky2ds8ppx5s5mhw&quot;]/div[@class=&quot;aok-relative&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-fixed-height&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>6a3f7991-a324-42a7-9a41-6e5b57942aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[3]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>6ab6440b-a055-46e6-8826-ab008aab31b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sponsored Ad - bianco di puro Professional Power Blender 1400 Watts with 8 Preset Options for Smoothies, Frozen Yogurt, Sa...']</value>
      <webElementGuid>5776d783-7afc-4240-9e86-5620171936ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/div/img</value>
      <webElementGuid>ab49c444-04fb-4a37-b742-9b9dfc71e413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/W/MEDIAX_849526-T2/images/I/31uI5jVZ9UL._AC_UY218_.jpg' and @alt = 'Sponsored Ad - bianco di puro Professional Power Blender 1400 Watts with 8 Preset Options for Smoothies, Frozen Yogurt, Sa...']</value>
      <webElementGuid>f1a8e63c-9c7d-48d5-801c-1aa800d55637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
